### PR TITLE
pymongo version 3 now supported

### PR DESCRIPTION
**Pull request by edouardpoitras**
Signed-off-by: Edouard Poitras <edouardpoitras@gmail.com>

### CODE REVIEW

**Comment by smarzola** [comment]
Hi, with pymongo 3 tests broke with `ConfigurationError: Unknown option max_pool_size`, you can check travis for the full traceback. The issue here is that MongoClient in pymongo 3 changed that option to maxPoolSize. If you provide a fix I'll be happy to merge your PR.

**Comment by edouardpoitras** [comment]
Hmm. Looks like my commit ruins your perfect coverage :S 
I'm not sure how we would go about testing both pymongo versions in tests...

For Python 2.6: Exception: amqp requires Python 2.7 or higher.
Also not sure what to do about that.

For Python 3.2 it looks like a coverall issue.

**Comment by smarzola** [comment]
I think that it's safe to support only pymongo 3 on the next release.
Last version of amqp that supports python 2.6 is 1.4.9, so we can force that version for python 2.6.
The issue with python 3.2 is with coverage >= 4, but let's make it easier and drop the support for python 3.2
Let me know if you want to submit those fixes by yourself, otherwise I'll do it.
Thanks

**Comment by edouardpoitras** [comment]
I changed the requirement for amqp to be >= 1.4.9 and still get the Python 2.7 required warning.

Feel free to add some finishing touches to get this working.

**Comment by edouardpoitras** [comment]
Ah, I just re-read your comment and realized you meant to do a <= 1.4.9 for Python 2.6. How would we explicitly specify that dependency for just Python 2.6?

**Pull request merged**
